### ISSUE TITLE
Change Folder icons in Details/Summary tags

### ISSUE THREAD

**Issue by dannluciano** [dannluciano/sendit-ide#13]
```css

#filesystem details > summary::marker {
  content: url('/assets/svgs/folder.svg');
}

#filesystem details[open] > summary::marker {
  content: url('/assets/svgs/folder-open.svg');
}

```

folder-open.svg
```svg
<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512" height='24' width='24'><path fill="#8aff80" d="M408 96H252.11a23.89 23.89 0 01-13.31-4L211 73.41A55.77 55.77 0 00179.89 64H104a56.06 56.06 0 00-56 56v24h416c0-30.88-25.12-48-56-48zM423.75 448H88.25a56 56 0 01-55.93-55.15L16.18 228.11v-.28A48 48 0 0164 176h384.1a48 48 0 0147.8 51.83v.28l-16.22 164.74A56 56 0 01423.75 448zm56.15-221.45z"/></svg>
```

folder.svg
```svg 
<svg xmlns="http://www.w3.org/2000/svg" class="ionicon" viewBox="0 0 512 512" height='24' width='24'><path fill="#8aff80" d="M496 152a56 56 0 00-56-56H220.11a23.89 23.89 0 01-13.31-4L179 73.41A55.77 55.77 0 00147.89 64H72a56 56 0 00-56 56v48a8 8 0 008 8h464a8 8 0 008-8zM16 392a56 56 0 0056 56h368a56 56 0 0056-56V216a8 8 0 00-8-8H24a8 8 0 00-8 8z"/></svg>
